version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_hash_key
        tests:
          - unique
          - not_null

  - name: dim_products
    columns:
      - name: product_hash_key
        tests:
          - unique
          - not_null

  - name: fact_transactions
    columns:
      - name: transaction_item_hash_key
        tests:
          - unique
          - not_null
      - name: customer_hash_key
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_hash_key
      - name: product_hash_key
        tests:
          - relationships:
              to: ref('dim_products')
              field: product_hash_key